import {
  blurData1,
  blurData2,
  blurData3,
  blurData4,
} from "../components/constants/blurDataUrl";
import { v4 as uuidv4 } from "uuid";
import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      firstName: "hardede",
      lastName: "hardede1",
      email: "admin@gmail.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      firstName: "hardede",
      lastName: "hardede1",
      email: "dimakostyuk50@gmail.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],

  sneakers: [
    {
      slug: "sneakers-voyage-nitro-gore-tex-men-s-running-shoes",
      imgProductPage: [
        { productImg: "/sneakers/voyage_nitro.webp" },
        { productImg: "/sneakers/voyage_nitro1.webp" },
        { productImg: "/sneakers/voyage_nitro2.webp" },
        { productImg: "/sneakers/voyage_nitro3.webp" },
      ],
      img: "/sneakers/voyage_nitro.webp",
      model: "Sneakers Voyage Nitro Gore-tex Men's Running Shoes",
      color: "Parasailing-CASTLEROCK-Puma Black",
      sizeSelection: [
        {
          sizeEur: 39,
          sizeUK: 6,
          sizeCountInStock: 6,
        },
        {
          sizeEur: 40,
          sizeUK: 6.5,
          sizeCountInStock: 2,
        },
        {
          sizeEur: 41,
          sizeUK: 7.5,
          sizeCountInStock: 5,
        },
        {
          sizeEur: 42,
          sizeUK: 8,
          sizeCountInStock: 0,
        },
        {
          sizeEur: 43,
          sizeUK: 9,
          sizeCountInStock: 1,
        },
        {
          sizeEur: 44,
          sizeUK: 9,
          sizeCountInStock: 9,
        },
      ],
      atr: "195167_01",
      alt: "Sneakers Voyage Nitro Gore-tex Men's Running Shoes",
      blur: { blurData1 },
      newPrice: 3090,
      oldPrice: 0,
      newPriceString: "3 090,00 ₴",
      oldPriceString: "0",
      sale: "",
    },
    {
      slug: "sneakers-voyage-nitro-gore-tex-men-s-running-shoes-black",
      imgProductPage: [
        { productImg: "/sneakers/voyage_nitro_black.webp" },
        { productImg: "/sneakers/voyage_nitro_black1.webp" },
        { productImg: "/sneakers/voyage_nitro_black2.webp" },
        { productImg: "/sneakers/voyage_nitro_black3.webp" },
        { productImg: "/sneakers/voyage_nitro_black4.webp" },
        { productImg: "/sneakers/voyage_nitro_black5.webp" },
      ],
      img: "/sneakers/voyage_nitro_black.webp",
      model: "Sneakers Voyage Nitro Gore-tex Men's Running Shoes",
      color: "Puma Black-Metallic Silver",
      sizeSelection: [
        {
          sizeEur: 39,
          sizeUK: 6,
          sizeCountInStock: 6,
        },
        {
          sizeEur: 40,
          sizeUK: 6.5,
          sizeCountInStock: 2,
        },
        {
          sizeEur: 41,
          sizeUK: 7.5,
          sizeCountInStock: 5,
        },
        {
          sizeEur: 42,
          sizeUK: 8,
          sizeCountInStock: 0,
        },
        {
          sizeEur: 43,
          sizeUK: 9,
          sizeCountInStock: 1,
        },
        {
          sizeEur: 44,
          sizeUK: 9,
          sizeCountInStock: 9,
        },
      ],
      atr: "195167_02",
      alt: "Sneakers Voyage Nitro Gore-tex Men's Running Shoes",
      blur: { blurData2 },
      newPrice: 3090,
      oldPrice: 7190,
      newPriceString: "3 090,00 ₴",
      oldPriceString: "7 190,00 ₴",
      sale: "-50%",
    },
    {
      slug: "sneakers-deviate-nitro-wtr-men-s-running-shoes",
      imgProductPage: [
        { productImg: "/sneakers/deviat_nitro.webp" },
        { productImg: "/sneakers/voyage_nitro_black1.webp" },
        { productImg: "/sneakers/voyage_nitro_black2.webp" },
        { productImg: "/sneakers/voyage_nitro_black3.webp" },
        { productImg: "/sneakers/voyage_nitro_black4.webp" },
        { productImg: "/sneakers/voyage_nitro_black5.webp" },
      ],
      img: "/sneakers/deviat_nitro.webp",
      model: "Sneakers Deviate Nitro Wtr Men's Running Shoes",
      color: "Puma Black",
      sizeSelection: [
        {
          sizeEur: 39,
          sizeUK: 6,
          sizeCountInStock: 6,
        },
        {
          sizeEur: 40,
          sizeUK: 6.5,
          sizeCountInStock: 2,
        },
        {
          sizeEur: 41,
          sizeUK: 7.5,
          sizeCountInStock: 5,
        },
        {
          sizeEur: 42,
          sizeUK: 8,
          sizeCountInStock: 0,
        },
        {
          sizeEur: 43,
          sizeUK: 9,
          sizeCountInStock: 1,
        },
        {
          sizeEur: 43,
          sizeUK: 9,
          sizeCountInStock: 9,
        },
      ],
      atr: "195572_01",
      alt: "Sneakers Deviate Nitro Wtr Men's Running Shoes",
      blur: { blurData3 },
      newPrice: 3390,
      oldPrice: 7690,
      newPriceString: "3 390,00 ₴",
      oldPriceString: "7 690,00 ₴",
      sale: "-50%",
    },
    {
      link: "/manPage",
      slug: "sneakers-twitch-runner-running-shoes",
      imgProductPage: [
        { productImg: "/sneakers/deviat_nitro.webp" },
        { productImg: "/sneakers/voyage_nitro_black1.webp" },
        { productImg: "/sneakers/voyage_nitro_black2.webp" },
        { productImg: "/sneakers/voyage_nitro_black3.webp" },
        { productImg: "/sneakers/voyage_nitro_black4.webp" },
        { productImg: "/sneakers/voyage_nitro_black5.webp" },
      ],
      img: "/sneakers/twitch_nitro.webp",
      model: "Sneakers Twitch Runner Running Shoes",
      color: "Peacoat-Puma White",
      sizeSelection: [
        {
          sizeEur: 39,
          sizeUK: 6,
          sizeCountInStock: 6,
        },
        {
          sizeEur: 40,
          sizeUK: 6.5,
          sizeCountInStock: 2,
        },
        {
          sizeEur: 41,
          sizeUK: 7.5,
          sizeCountInStock: 5,
        },
        {
          sizeEur: 42,
          sizeUK: 8,
          sizeCountInStock: 0,
        },
        {
          sizeEur: 43,
          sizeUK: 9,
          sizeCountInStock: 1,
        },
        {
          sizeEur: 43,
          sizeUK: 9,
          sizeCountInStock: 9,
        },
      ],
      atr: "376289_05",
      alt: "Sneakers Twitch Runner Running Shoes",
      blur: { blurData4 },
      newPrice: 1500,
      oldPrice: 2590,
      newPriceString: "1 500,00 ₴",
      oldPriceString: "2 590,00 ₴",
      sale: "-50%",
    },
    {
      link: "/manPage",
      slug: "sneakers-twitch-runner-running-shoes",
      imgProductPage: [
        { productImg: "/sneakers/deviat_nitro.webp" },
        { productImg: "/sneakers/voyage_nitro_black1.webp" },
        { productImg: "/sneakers/voyage_nitro_black2.webp" },
        { productImg: "/sneakers/voyage_nitro_black3.webp" },
        { productImg: "/sneakers/voyage_nitro_black4.webp" },
        { productImg: "/sneakers/voyage_nitro_black5.webp" },
      ],
      img: "/sneakers/twitch_nitro.webp",
      model: "Sneakers Twitch Runner Running Shoes",
      color: "Peacoat-Puma White",
      sizeSelection: [
        {
          sizeEur: 39,
          sizeUK: 6,
          sizeCountInStock: 6,
        },
        {
          sizeEur: 40,
          sizeUK: 6.5,
          sizeCountInStock: 2,
        },
        {
          sizeEur: 41,
          sizeUK: 7.5,
          sizeCountInStock: 5,
        },
        {
          sizeEur: 42,
          sizeUK: 8,
          sizeCountInStock: 0,
        },
        {
          sizeEur: 43,
          sizeUK: 9,
          sizeCountInStock: 1,
        },
        {
          sizeEur: 43,
          sizeUK: 9,
          sizeCountInStock: 9,
        },
      ],
      alt: "Sneakers Twitch Runner Running Shoes",
      blur: { blurData4 },
      newPrice: 1500,
      oldPrice: 2590,
      newPriceString: "1 500,00 ₴",
      oldPriceString: "2 590,00 ₴",
      sale: "-50%",
    },
    {
      link: "/manPage",
      slug: "sneakers-twitch-runner-running-shoes",
      imgProductPage: [
        { productImg: "/sneakers/deviat_nitro.webp" },
        { productImg: "/sneakers/voyage_nitro_black1.webp" },
        { productImg: "/sneakers/voyage_nitro_black2.webp" },
        { productImg: "/sneakers/voyage_nitro_black3.webp" },
        { productImg: "/sneakers/voyage_nitro_black4.webp" },
        { productImg: "/sneakers/voyage_nitro_black5.webp" },
      ],
      img: "/sneakers/twitch_nitro.webp",
      model: "Sneakers Twitch Runner Running Shoes",
      color: "Peacoat-Puma White",
      sizeSelection: [
        {
          sizeEur: 39,
          sizeUK: 6,
          sizeCountInStock: 6,
        },
        {
          sizeEur: 40,
          sizeUK: 6.5,
          sizeCountInStock: 2,
        },
        {
          sizeEur: 41,
          sizeUK: 7.5,
          sizeCountInStock: 5,
        },
        {
          sizeEur: 42,
          sizeUK: 8,
          sizeCountInStock: 0,
        },
        {
          sizeEur: 43,
          sizeUK: 9,
          sizeCountInStock: 1,
        },
        {
          sizeEur: 43,
          sizeUK: 9,
          sizeCountInStock: 9,
        },
      ],
      alt: "Sneakers Twitch Runner Running Shoes",
      blur: { blurData4 },
      newPrice: 1500,
      oldPrice: 2590,
      newPriceString: "1 500,00 ₴",
      oldPriceString: "2 590,00 ₴",
      sale: "-50%",
    },
  ],

  sneakersMan: [
    {
      slug: "sneakers-voyage-nitro-gore-tex-men-s-running-shoes",
      imgProductPage: [
        { productImg: "/sneakers/voyage_nitro.webp" },
        { productImg: "/sneakers/voyage_nitro1.webp" },
        { productImg: "/sneakers/voyage_nitro2.webp" },
        { productImg: "/sneakers/voyage_nitro3.webp" },
      ],
      img: "/sneakers/voyage_nitro.webp",
      model: "Sneakers Voyage Nitro Gore-tex Men's Running Shoes",
      color: "Parasailing-CASTLEROCK-Puma Black",
      sizeSelection: [
        {
          sizeEur: 39,
          sizeUK: 6,
          sizeCountInStock: 6,
        },
        {
          sizeEur: 40,
          sizeUK: 6.5,
          sizeCountInStock: 2,
        },
        {
          sizeEur: 41,
          sizeUK: 7.5,
          sizeCountInStock: 5,
        },
        {
          sizeEur: 42,
          sizeUK: 8,
          sizeCountInStock: 0,
        },
        {
          sizeEur: 43,
          sizeUK: 9,
          sizeCountInStock: 1,
        },
        {
          sizeEur: 44,
          sizeUK: 9,
          sizeCountInStock: 9,
        },
      ],
      atr: "195167_01",
      alt: "Sneakers Voyage Nitro Gore-tex Men's Running Shoes",
      blur: { blurData1 },
      newPrice: 3090,
      oldPrice: 0,
      newPriceString: "3 090,00 ₴",
      oldPriceString: "0",
    },
    {
      slug: "sneakers-voyage-nitro-gore-tex-men-s-running-shoes-black",
      imgProductPage: [
        { productImg: "/sneakers/voyage_nitro_black.webp" },
        { productImg: "/sneakers/voyage_nitro_black1.webp" },
        { productImg: "/sneakers/voyage_nitro_black2.webp" },
        { productImg: "/sneakers/voyage_nitro_black3.webp" },
        { productImg: "/sneakers/voyage_nitro_black4.webp" },
        { productImg: "/sneakers/voyage_nitro_black5.webp" },
      ],
      img: "/sneakers/voyage_nitro_black.webp",
      model: "Sneakers Voyage Nitro Gore-tex Men's Running Shoes",
      color: "Puma Black-Metallic Silver",
      sizeSelection: [
        {
          sizeEur: 39,
          sizeUK: 6,
          sizeCountInStock: 6,
        },
        {
          sizeEur: 40,
          sizeUK: 6.5,
          sizeCountInStock: 2,
        },
        {
          sizeEur: 41,
          sizeUK: 7.5,
          sizeCountInStock: 5,
        },
        {
          sizeEur: 42,
          sizeUK: 8,
          sizeCountInStock: 0,
        },
        {
          sizeEur: 43,
          sizeUK: 9,
          sizeCountInStock: 1,
        },
        {
          sizeEur: 44,
          sizeUK: 9,
          sizeCountInStock: 9,
        },
      ],
      atr: "195167_02",
      alt: "Sneakers Voyage Nitro Gore-tex Men's Running Shoes",
      blur: { blurData2 },
      newPrice: 3090,
      oldPrice: 7190,
      newPriceString: "3 090,00 ₴",
      oldPriceString: "7 190,00 ₴",
      sale: "-54%",
    },
    {
      slug: "sneakers-deviate-nitro-wtr-men-s-running-shoes",
      imgProductPage: [
        { productImg: "/sneakers/deviat_nitro.webp" },
        { productImg: "/sneakers/voyage_nitro_black1.webp" },
        { productImg: "/sneakers/voyage_nitro_black2.webp" },
        { productImg: "/sneakers/voyage_nitro_black3.webp" },
        { productImg: "/sneakers/voyage_nitro_black4.webp" },
        { productImg: "/sneakers/voyage_nitro_black5.webp" },
      ],
      img: "/sneakers/deviat_nitro.webp",
      model: "Sneakers Deviate Nitro Wtr Men's Running Shoes",
      color: "Puma Black",
      sizeSelection: [
        {
          sizeEur: 39,
          sizeUK: 6,
          sizeCountInStock: 6,
        },
        {
          sizeEur: 40,
          sizeUK: 6.5,
          sizeCountInStock: 2,
        },
        {
          sizeEur: 41,
          sizeUK: 7.5,
          sizeCountInStock: 2,
        },
        {
          sizeEur: 42,
          sizeUK: 8,
          sizeCountInStock: 5,
        },
        {
          sizeEur: 43,
          sizeUK: 9,
          sizeCountInStock: 1,
        },
        {
          sizeEur: 44,
          sizeUK: 9,
          sizeCountInStock: 9,
        },
      ],
      atr: "195572_01",
      alt: "Sneakers Deviate Nitro Wtr Men's Running Shoes",
      blur: { blurData3 },
      newPrice: 3390,
      oldPrice: 7690,
      newPriceString: "3 390,00 ₴",
      oldPriceString: "7 690,00 ₴",
      sale: "-53%",
    },
    {
      slug: "sneakers-deviate-nitro-wtr-men-s-running-shoes1",
      imgProductPage: [
        { productImg: "/sneakers/deviat_nitro.webp" },
        { productImg: "/sneakers/voyage_nitro_black1.webp" },
        { productImg: "/sneakers/voyage_nitro_black2.webp" },
        { productImg: "/sneakers/voyage_nitro_black3.webp" },
        { productImg: "/sneakers/voyage_nitro_black4.webp" },
        { productImg: "/sneakers/voyage_nitro_black5.webp" },
      ],
      img: "/sneakers/deviat_nitro.webp",
      model: "Sneakers Deviate Nitro Wtr Men's Running Shoes",
      color: "Puma Black",
      sizeSelection: [
        {
          sizeEur: 39,
          sizeUK: 6,
          sizeCountInStock: 6,
        },
        {
          sizeEur: 40,
          sizeUK: 6.5,
          sizeCountInStock: 2,
        },
        {
          sizeEur: 41,
          sizeUK: 7.5,
          sizeCountInStock: 2,
        },
        {
          sizeEur: 42,
          sizeUK: 8,
          sizeCountInStock: 5,
        },
        {
          sizeEur: 43,
          sizeUK: 9,
          sizeCountInStock: 1,
        },
        {
          sizeEur: 44,
          sizeUK: 9,
          sizeCountInStock: 9,
        },
      ],
      atr: "195572_01",
      alt: "Sneakers Deviate Nitro Wtr Men's Running Shoes",
      blur: { blurData3 },
      newPrice: 3390,
      oldPrice: 7690,
      newPriceString: "3 390,00 ₴",
      oldPriceString: "7 690,00 ₴",
      sale: "-53%",
    },
    {
      slug: "sneakers-twitch-runner-running-shoes",
      imgProductPage: [
        { productImg: "/sneakers/deviat_nitro.webp" },
        { productImg: "/sneakers/voyage_nitro_black1.webp" },
        { productImg: "/sneakers/voyage_nitro_black2.webp" },
        { productImg: "/sneakers/voyage_nitro_black3.webp" },
        { productImg: "/sneakers/voyage_nitro_black4.webp" },
        { productImg: "/sneakers/voyage_nitro_black5.webp" },
      ],
      img: "/sneakers/twitch_nitro.webp",
      model: "Sneakers Twitch Runner Running Shoes",
      color: "Peacoat Puma White",
      sizeSelection: [
        {
          sizeEur: 39,
          sizeUK: 6,
          sizeCountInStock: 6,
        },
        {
          sizeEur: 40,
          sizeUK: 6.5,
          sizeCountInStock: 2,
        },
        {
          sizeEur: 41,
          sizeUK: 7.5,
          sizeCountInStock: 2,
        },
        {
          sizeEur: 42,
          sizeUK: 8,
          sizeCountInStock: 5,
        },
        {
          sizeEur: 43,
          sizeUK: 9,
          sizeCountInStock: 1,
        },
        {
          sizeEur: 44,
          sizeUK: 9,
          sizeCountInStock: 9,
        },
      ],
      atr: "195572_01",
      alt: "Sneakers Deviate Nitro Wtr Men's Running Shoes",
      blur: { blurData3 },
      newPrice: 3390,
      oldPrice: 7690,
      newPriceString: "3 390,00 ₴",
      oldPriceString: "7 690,00 ₴",
      sale: "-53%",
    },
    {
      slug: "sneakers-twitch-runner-running-shoes",
      imgProductPage: [
        { productImg: "/sneakers/deviat_nitro.webp" },
        { productImg: "/sneakers/voyage_nitro_black1.webp" },
        { productImg: "/sneakers/voyage_nitro_black2.webp" },
        { productImg: "/sneakers/voyage_nitro_black3.webp" },
        { productImg: "/sneakers/voyage_nitro_black4.webp" },
        { productImg: "/sneakers/voyage_nitro_black5.webp" },
      ],
      img: "/sneakers/twitch_nitro.webp",
      model: "Sneakers Twitch Runner Running Shoes",
      color: "Peacoat-Puma White",
      sizeSelection: [
        {
          sizeEur: 39,
          sizeUK: 6,
          sizeCountInStock: 6,
        },
        {
          sizeEur: 40,
          sizeUK: 6.5,
          sizeCountInStock: 2,
        },
        {
          sizeEur: 41,
          sizeUK: 7.5,
          sizeCountInStock: 2,
        },
        {
          sizeEur: 42,
          sizeUK: 8,
          sizeCountInStock: 5,
        },
        {
          sizeEur: 43,
          sizeUK: 9,
          sizeCountInStock: 1,
        },
        {
          sizeEur: 44,
          sizeUK: 9,
          sizeCountInStock: 9,
        },
      ],
      atr: "195572_01",
      alt: "Sneakers Deviate Nitro Wtr Men's Running Shoes",
      blur: { blurData3 },
      newPrice: 3390,
      oldPrice: 7690,
      newPriceString: "3 390,00 ₴",
      oldPriceString: "7 690,00 ₴",
      sale: "-53%",
    },
  ],
  sneakersWoman: [
    {
      slug: "sneakers-pwrframe_op-1-trail",
      imgProductPage: [
        {
          productImg:
            "/sneakersWoman/pwrframe_op-1/pwrframe_op-1_trail_sneakers.webp",
        },
        {
          productImg:
            "/sneakersWoman/pwrframe_op-1/pwrframe_op-1_trail_sneakers1.webp",
        },
        {
          productImg:
            "/sneakersWoman/pwrframe_op-1/pwrframe_op-1_trail_sneakers2.webp",
        },
        {
          productImg:
            "/sneakersWoman/pwrframe_op-1/pwrframe_op-1_trail_sneakers3.webp",
        },
        {
          productImg:
            "/sneakersWoman/pwrframe_op-1/pwrframe_op-1_trail_sneakers4.webp",
        },
        {
          productImg:
            "/sneakersWoman/pwrframe_op-1/pwrframe_op-1_trail_sneakers5.webp",
        },
        {
          productImg:
            "/sneakersWoman/pwrframe_op-1/pwrframe_op-1_trail_sneakers6.webp",
        },
        {
          productImg:
            "/sneakersWoman/pwrframe_op-1/pwrframe_op-1_trail_sneakers7.webp",
        },
      ],
      img: "/sneakersWoman/pwrframe_op-1/pwrframe_op-1_trail_sneakers.webp",
      model: "Sneakers Pwrframe Op-1 Trail",
      color: "Gray Violet-Puma Black",
      sizeSelection: [
        {
          sizeEur: 39,
          sizeUK: 6,
          sizeCountInStock: 6,
        },
        {
          sizeEur: 40,
          sizeUK: 6.5,
          sizeCountInStock: 2,
        },
        {
          sizeEur: 41,
          sizeUK: 7.5,
          sizeCountInStock: 5,
        },
        {
          sizeEur: 42,
          sizeUK: 8,
          sizeCountInStock: 0,
        },
        {
          sizeEur: 43,
          sizeUK: 9,
          sizeCountInStock: 1,
        },
        {
          sizeEur: 44,
          sizeUK: 9,
          sizeCountInStock: 9,
        },
      ],
      atr: "386378_01",
      alt: "pwrframe_op-1_trail_sneakers",
      blur: { blurData1 },
      newPrice: 5690,
      oldPrice: 0,
      newPriceString: "5 690,00 ₴",
      oldPriceString: "0",
    },
    {
      slug: "sneakers-slipstream-mid",
      imgProductPage: [
        { productImg: "/sneakersWoman/slipstream_mid/slipstream_mid.webp" },
        { productImg: "/sneakersWoman/slipstream_mid/slipstream_mid1.webp" },
        { productImg: "/sneakersWoman/slipstream_mid/slipstream_mid2.webp" },
        { productImg: "/sneakersWoman/slipstream_mid/slipstream_mid3.webp" },
        { productImg: "/sneakersWoman/slipstream_mid/slipstream_mid4.webp" },
        { productImg: "/sneakersWoman/slipstream_mid/slipstream_mid5.webp" },
        { productImg: "/sneakersWoman/slipstream_mid/slipstream_mid6.webp" },
      ],
      img: "/sneakersWoman/slipstream_mid/slipstream_mid.webp",
      model: "Sneakers SLIPSTREAM MID",
      color: "Puma White-Glacier Gray",
      sizeSelection: [
        {
          sizeEur: 39,
          sizeUK: 6,
          sizeCountInStock: 6,
        },
        {
          sizeEur: 40,
          sizeUK: 6.5,
          sizeCountInStock: 2,
        },
        {
          sizeEur: 41,
          sizeUK: 7.5,
          sizeCountInStock: 5,
        },
        {
          sizeEur: 42,
          sizeUK: 8,
          sizeCountInStock: 0,
        },
        {
          sizeEur: 43,
          sizeUK: 9,
          sizeCountInStock: 1,
        },
        {
          sizeEur: 44,
          sizeUK: 9,
          sizeCountInStock: 9,
        },
      ],
      atr: "386565_02",
      alt: "slipstream_mid",
      blur: { blurData2 },
      newPrice: 4590,
      oldPrice: 0,
      newPriceString: "4 590,00 ₴",
      oldPriceString: "0",
    },
    {
      slug: "sneakers-orkid-retro-grade",
      imgProductPage: [
        { productImg: "/sneakersWoman/orkid_retro/orkid_retro_grade.webp" },
        { productImg: "/sneakersWoman/orkid_retro/orkid_retro_grade1.webp" },
        { productImg: "/sneakersWoman/orkid_retro/orkid_retro_grade2.webp" },
        { productImg: "/sneakersWoman/orkid_retro/orkid_retro_grade3.webp" },
        { productImg: "/sneakersWoman/orkid_retro/orkid_retro_grade4.webp" },
        { productImg: "/sneakersWoman/orkid_retro/orkid_retro_grade5.webp" },
      ],
      img: "/sneakersWoman/orkid_retro/orkid_retro_grade.webp",
      model: "Sneakers Orkid Retro Grade Woman",
      color: "Vaporous Gray-Burnt Red",
      sizeSelection: [
        {
          sizeEur: 39,
          sizeUK: 6,
          sizeCountInStock: 6,
        },
        {
          sizeEur: 40,
          sizeUK: 6.5,
          sizeCountInStock: 2,
        },
        {
          sizeEur: 41,
          sizeUK: 7.5,
          sizeCountInStock: 2,
        },
        {
          sizeEur: 42,
          sizeUK: 8,
          sizeCountInStock: 5,
        },
        {
          sizeEur: 43,
          sizeUK: 9,
          sizeCountInStock: 1,
        },
        {
          sizeEur: 44,
          sizeUK: 9,
          sizeCountInStock: 9,
        },
      ],
      atr: "387465_01",
      alt: "sneakers-orkid_retro_grade",
      blur: { blurData3 },
      newPrice: 5190,
      oldPrice: 9690,
      newPriceString: "5 190,00 ₴",
      oldPriceString: "9 690,00 ₴",
      sale: "-55%",
    },
    {
      slug: "sneakers-carina-lift-mono",
      imgProductPage: [
        { productImg: "/sneakersWoman/carina_lift/carina_lift_mono.webp" },
        { productImg: "/sneakersWoman/carina_lift/carina_lift_mono1.webp" },
        { productImg: "/sneakersWoman/carina_lift/carina_lift_mono2.webp" },
        { productImg: "/sneakersWoman/carina_lift/carina_lift_mono3.webp" },
        { productImg: "/sneakersWoman/carina_lift/carina_lift_mono4.webp" },
        { productImg: "/sneakersWoman/carina_lift/carina_lift_mono5.webp" },
        { productImg: "/sneakersWoman/carina_lift/carina_lift_mono6.webp" },
      ],
      img: "/sneakersWoman/carina_lift/carina_lift_mono.webp",
      model: "Sneakers Carina Lift Mono Woman",
      color: "Puma Black-Puma White",
      sizeSelection: [
        {
          sizeEur: 39,
          sizeUK: 6,
          sizeCountInStock: 6,
        },
        {
          sizeEur: 40,
          sizeUK: 6.5,
          sizeCountInStock: 2,
        },
        {
          sizeEur: 41,
          sizeUK: 7.5,
          sizeCountInStock: 2,
        },
        {
          sizeEur: 42,
          sizeUK: 8,
          sizeCountInStock: 5,
        },
        {
          sizeEur: 43,
          sizeUK: 9,
          sizeCountInStock: 1,
        },
        {
          sizeEur: 44,
          sizeUK: 9,
          sizeCountInStock: 9,
        },
      ],
      atr: "386405_01",
      alt: "carina_lift_mono",
      blur: { blurData3 },
      newPrice: 2890,
      oldPrice: 0,
      newPriceString: "2 990,00 ₴",
      oldPriceString: "0",
    },
    {
      slug: "sneakers-puma-palomo-nitefox",
      imgProductPage: [
        { productImg: "/sneakersWoman/puma_palomo/puma_palomo_nitefox.webp" },
        { productImg: "/sneakersWoman/puma_palomo/puma_palomo_nitefox1.webp" },
        { productImg: "/sneakersWoman/puma_palomo/puma_palomo_nitefox2.webp" },
        { productImg: "/sneakersWoman/puma_palomo/puma_palomo_nitefox3.webp" },
        { productImg: "/sneakersWoman/puma_palomo/puma_palomo_nitefox4.webp" },
        { productImg: "/sneakersWoman/puma_palomo/puma_palomo_nitefox5.webp" },
      ],
      img: "/sneakersWoman/puma_palomo/puma_palomo_nitefox.webp",
      model: "Puma X Palomo Nitefox Loafers",
      color: "Puma Black",
      sizeSelection: [
        {
          sizeEur: 39,
          sizeUK: 6,
          sizeCountInStock: 6,
        },
        {
          sizeEur: 40,
          sizeUK: 6.5,
          sizeCountInStock: 2,
        },
        {
          sizeEur: 41,
          sizeUK: 7.5,
          sizeCountInStock: 2,
        },
        {
          sizeEur: 42,
          sizeUK: 8,
          sizeCountInStock: 5,
        },
        {
          sizeEur: 43,
          sizeUK: 9,
          sizeCountInStock: 1,
        },
        {
          sizeEur: 44,
          sizeUK: 9,
          sizeCountInStock: 9,
        },
      ],
      atr: "388441_01",
      alt: "puma_palomo_nitefox",
      blur: { blurData3 },
      newPrice: 22990,
      oldPrice: 0,
      newPriceString: "22 990,00 ₴",
      oldPriceString: "0",
    },
  ],
};

export default data;
