import {
  blurData1,
  blurData2,
  blurData3,
  blurData4,
} from "../components/constants/blurDataUrl";
import { v4 as uuidv4 } from "uuid";

const data = {
  sneakers: [
    {
      id: uuidv4(),
      slug: "sneakers-voyage-nitro-gore-tex-men-s-running-shoes",
      imgProductPage: [
        { productImg: "/sneakers/voyage_nitro.webp" },
        { productImg: "/sneakers/voyage_nitro1.webp" },
        { productImg: "/sneakers/voyage_nitro2.webp" },
        { productImg: "/sneakers/voyage_nitro3.webp" },
      ],
      img: "/sneakers/voyage_nitro.webp",
      model: "Sneakers Voyage Nitro Gore-tex Men's Running Shoes",
      color: "Parasailing-CASTLEROCK-Puma Black",
      sizeSelection: [
        {
          sizeEur: 39,
          sizeUK: 6,
          sizeCountInStock: 6,
        },
        {
          sizeEur: 40,
          sizeUK: 6.5,
          sizeCountInStock: 2,
        },
        {
          sizeEur: 41,
          sizeUK: 7.5,
          sizeCountInStock: 5,
        },
        {
          sizeEur: 42,
          sizeUK: 8,
          sizeCountInStock: 0,
        },
        {
          sizeEur: 43,
          sizeUK: 9,
          sizeCountInStock: 1,
        },
        {
          sizeEur: 44,
          sizeUK: 9,
          sizeCountInStock: 9,
        },
      ],
      atr: "195167_01",
      alt: "Sneakers Voyage Nitro Gore-tex Men's Running Shoes",
      blur: { blurData1 },
      newPrice: 3090,
      oldPrice: 0,
      newPriceString: "3 090,00 ₴",
      oldPriceString: "0",
      sale: "",
    },
    {
      id: uuidv4(),
      slug: "sneakers-voyage-nitro-gore-tex-men-s-running-shoes-black",
      imgProductPage: [
        { productImg: "/sneakers/voyage_nitro_black.webp" },
        { productImg: "/sneakers/voyage_nitro_black1.webp" },
        { productImg: "/sneakers/voyage_nitro_black2.webp" },
        { productImg: "/sneakers/voyage_nitro_black3.webp" },
        { productImg: "/sneakers/voyage_nitro_black4.webp" },
        { productImg: "/sneakers/voyage_nitro_black5.webp" },
      ],
      img: "/sneakers/voyage_nitro_black.webp",
      model: "Sneakers Voyage Nitro Gore-tex Men's Running Shoes",
      color: "Puma Black-Metallic Silver",
      sizeSelection: [
        {
          sizeEur: 39,
          sizeUK: 6,
          sizeCountInStock: 6,
        },
        {
          sizeEur: 40,
          sizeUK: 6.5,
          sizeCountInStock: 2,
        },
        {
          sizeEur: 41,
          sizeUK: 7.5,
          sizeCountInStock: 5,
        },
        {
          sizeEur: 42,
          sizeUK: 8,
          sizeCountInStock: 0,
        },
        {
          sizeEur: 43,
          sizeUK: 9,
          sizeCountInStock: 1,
        },
        {
          sizeEur: 44,
          sizeUK: 9,
          sizeCountInStock: 9,
        },
      ],
      atr: "195167_02",
      alt: "Sneakers Voyage Nitro Gore-tex Men's Running Shoes",
      blur: { blurData2 },
      newPrice: 3090,
      oldPrice: 7190,
      newPriceString: "3 090,00 ₴",
      oldPriceString: "7 190,00 ₴",
      sale: "-50%",
    },
    {
      id: uuidv4(),
      slug: "sneakers-deviate-nitro-wtr-men-s-running-shoes",
      imgProductPage: [
        { productImg: "/sneakers/deviat_nitro.webp" },
        { productImg: "/sneakers/voyage_nitro_black1.webp" },
        { productImg: "/sneakers/voyage_nitro_black2.webp" },
        { productImg: "/sneakers/voyage_nitro_black3.webp" },
        { productImg: "/sneakers/voyage_nitro_black4.webp" },
        { productImg: "/sneakers/voyage_nitro_black5.webp" },
      ],
      img: "/sneakers/deviat_nitro.webp",
      model: "Sneakers Deviate Nitro Wtr Men's Running Shoes",
      color: "Puma Black",
      sizeSelection: [
        {
          sizeEur: 39,
          sizeUK: 6,
          sizeCountInStock: 6,
        },
        {
          sizeEur: 40,
          sizeUK: 6.5,
          sizeCountInStock: 2,
        },
        {
          sizeEur: 41,
          sizeUK: 7.5,
          sizeCountInStock: 5,
        },
        {
          sizeEur: 42,
          sizeUK: 8,
          sizeCountInStock: 0,
        },
        {
          sizeEur: 43,
          sizeUK: 9,
          sizeCountInStock: 1,
        },
        {
          sizeEur: 43,
          sizeUK: 9,
          sizeCountInStock: 9,
        },
      ],
      atr: "195572_01",
      alt: "Sneakers Deviate Nitro Wtr Men's Running Shoes",
      blur: { blurData3 },
      newPrice: 3390,
      oldPrice: 7690,
      newPriceString: "3 390,00 ₴",
      oldPriceString: "7 690,00 ₴",
      sale: "-50%",
    },
    {
      id: uuidv4(),
      link: "/manPage",
      slug: "sneakers-twitch-runner-running-shoes",
      imgProductPage: [
        { productImg: "/sneakers/deviat_nitro.webp" },
        { productImg: "/sneakers/voyage_nitro_black1.webp" },
        { productImg: "/sneakers/voyage_nitro_black2.webp" },
        { productImg: "/sneakers/voyage_nitro_black3.webp" },
        { productImg: "/sneakers/voyage_nitro_black4.webp" },
        { productImg: "/sneakers/voyage_nitro_black5.webp" },
      ],
      img: "/sneakers/twitch_nitro.webp",
      model: "Sneakers Twitch Runner Running Shoes",
      color: "Peacoat-Puma White",
      sizeSelection: [
        {
          sizeEur: 39,
          sizeUK: 6,
          sizeCountInStock: 6,
        },
        {
          sizeEur: 40,
          sizeUK: 6.5,
          sizeCountInStock: 2,
        },
        {
          sizeEur: 41,
          sizeUK: 7.5,
          sizeCountInStock: 5,
        },
        {
          sizeEur: 42,
          sizeUK: 8,
          sizeCountInStock: 0,
        },
        {
          sizeEur: 43,
          sizeUK: 9,
          sizeCountInStock: 1,
        },
        {
          sizeEur: 43,
          sizeUK: 9,
          sizeCountInStock: 9,
        },
      ],
      atr: "376289_05",
      alt: "Sneakers Twitch Runner Running Shoes",
      blur: { blurData4 },
      newPrice: 1500,
      oldPrice: 2590,
      newPriceString: "1 500,00 ₴",
      oldPriceString: "2 590,00 ₴",
      sale: "-50%",
    },
    {
      id: uuidv4(),
      link: "/manPage",
      slug: "sneakers-twitch-runner-running-shoes",
      imgProductPage: [
        { productImg: "/sneakers/deviat_nitro.webp" },
        { productImg: "/sneakers/voyage_nitro_black1.webp" },
        { productImg: "/sneakers/voyage_nitro_black2.webp" },
        { productImg: "/sneakers/voyage_nitro_black3.webp" },
        { productImg: "/sneakers/voyage_nitro_black4.webp" },
        { productImg: "/sneakers/voyage_nitro_black5.webp" },
      ],
      img: "/sneakers/twitch_nitro.webp",
      model: "Sneakers Twitch Runner Running Shoes",
      color: "Peacoat-Puma White",
      sizeSelection: [
        {
          sizeEur: 39,
          sizeUK: 6,
          sizeCountInStock: 6,
        },
        {
          sizeEur: 40,
          sizeUK: 6.5,
          sizeCountInStock: 2,
        },
        {
          sizeEur: 41,
          sizeUK: 7.5,
          sizeCountInStock: 5,
        },
        {
          sizeEur: 42,
          sizeUK: 8,
          sizeCountInStock: 0,
        },
        {
          sizeEur: 43,
          sizeUK: 9,
          sizeCountInStock: 1,
        },
        {
          sizeEur: 43,
          sizeUK: 9,
          sizeCountInStock: 9,
        },
      ],
      alt: "Sneakers Twitch Runner Running Shoes",
      blur: { blurData4 },
      newPrice: 1500,
      oldPrice: 2590,
      newPriceString: "1 500,00 ₴",
      oldPriceString: "2 590,00 ₴",
      sale: "-50%",
    },
    {
      id: uuidv4(),
      link: "/manPage",
      slug: "sneakers-twitch-runner-running-shoes",
      imgProductPage: [
        { productImg: "/sneakers/deviat_nitro.webp" },
        { productImg: "/sneakers/voyage_nitro_black1.webp" },
        { productImg: "/sneakers/voyage_nitro_black2.webp" },
        { productImg: "/sneakers/voyage_nitro_black3.webp" },
        { productImg: "/sneakers/voyage_nitro_black4.webp" },
        { productImg: "/sneakers/voyage_nitro_black5.webp" },
      ],
      img: "/sneakers/twitch_nitro.webp",
      model: "Sneakers Twitch Runner Running Shoes",
      color: "Peacoat-Puma White",
      sizeSelection: [
        {
          sizeEur: 39,
          sizeUK: 6,
          sizeCountInStock: 6,
        },
        {
          sizeEur: 40,
          sizeUK: 6.5,
          sizeCountInStock: 2,
        },
        {
          sizeEur: 41,
          sizeUK: 7.5,
          sizeCountInStock: 5,
        },
        {
          sizeEur: 42,
          sizeUK: 8,
          sizeCountInStock: 0,
        },
        {
          sizeEur: 43,
          sizeUK: 9,
          sizeCountInStock: 1,
        },
        {
          sizeEur: 43,
          sizeUK: 9,
          sizeCountInStock: 9,
        },
      ],
      alt: "Sneakers Twitch Runner Running Shoes",
      blur: { blurData4 },
      newPrice: 1500,
      oldPrice: 2590,
      newPriceString: "1 500,00 ₴",
      oldPriceString: "2 590,00 ₴",
      sale: "-50%",
    },
  ],

  sneakersMan: [
    {
      id: uuidv4(),
      slug: "sneakers-voyage-nitro-gore-tex-men-s-running-shoes",
      imgProductPage: [
        { productImg: "/sneakers/voyage_nitro.webp" },
        { productImg: "/sneakers/voyage_nitro1.webp" },
        { productImg: "/sneakers/voyage_nitro2.webp" },
        { productImg: "/sneakers/voyage_nitro3.webp" },
      ],
      img: "/sneakers/voyage_nitro.webp",
      model: "Sneakers Voyage Nitro Gore-tex Men's Running Shoes",
      color: "Parasailing-CASTLEROCK-Puma Black",
      sizeSelection: [
        {
          sizeEur: 39,
          sizeUK: 6,
          sizeCountInStock: 6,
        },
        {
          sizeEur: 40,
          sizeUK: 6.5,
          sizeCountInStock: 2,
        },
        {
          sizeEur: 41,
          sizeUK: 7.5,
          sizeCountInStock: 5,
        },
        {
          sizeEur: 42,
          sizeUK: 8,
          sizeCountInStock: 0,
        },
        {
          sizeEur: 43,
          sizeUK: 9,
          sizeCountInStock: 1,
        },
        {
          sizeEur: 44,
          sizeUK: 9,
          sizeCountInStock: 9,
        },
      ],
      atr: "195167_01",
      alt: "Sneakers Voyage Nitro Gore-tex Men's Running Shoes",
      blur: { blurData1 },
      newPrice: 3090,
      oldPrice: 0,
      newPriceString: "3 090,00 ₴",
      oldPriceString: "0",
    },
    {
      id: uuidv4(),
      slug: "sneakers-voyage-nitro-gore-tex-men-s-running-shoes-black",
      imgProductPage: [
        { productImg: "/sneakers/voyage_nitro_black.webp" },
        { productImg: "/sneakers/voyage_nitro_black1.webp" },
        { productImg: "/sneakers/voyage_nitro_black2.webp" },
        { productImg: "/sneakers/voyage_nitro_black3.webp" },
        { productImg: "/sneakers/voyage_nitro_black4.webp" },
        { productImg: "/sneakers/voyage_nitro_black5.webp" },
      ],
      img: "/sneakers/voyage_nitro_black.webp",
      model: "Sneakers Voyage Nitro Gore-tex Men's Running Shoes",
      color: "Puma Black-Metallic Silver",
      sizeSelection: [
        {
          sizeEur: 39,
          sizeUK: 6,
          sizeCountInStock: 6,
        },
        {
          sizeEur: 40,
          sizeUK: 6.5,
          sizeCountInStock: 2,
        },
        {
          sizeEur: 41,
          sizeUK: 7.5,
          sizeCountInStock: 5,
        },
        {
          sizeEur: 42,
          sizeUK: 8,
          sizeCountInStock: 0,
        },
        {
          sizeEur: 43,
          sizeUK: 9,
          sizeCountInStock: 1,
        },
        {
          sizeEur: 44,
          sizeUK: 9,
          sizeCountInStock: 9,
        },
      ],
      atr: "195167_02",
      alt: "Sneakers Voyage Nitro Gore-tex Men's Running Shoes",
      blur: { blurData2 },
      newPrice: 3090,
      oldPrice: 7190,
      newPriceString: "3 090,00 ₴",
      oldPriceString: "7 190,00 ₴",
      sale: "-54%",
    },
    {
      id: uuidv4(),
      slug: "sneakers-deviate-nitro-wtr-men-s-running-shoes",
      imgProductPage: [
        { productImg: "/sneakers/deviat_nitro.webp" },
        { productImg: "/sneakers/voyage_nitro_black1.webp" },
        { productImg: "/sneakers/voyage_nitro_black2.webp" },
        { productImg: "/sneakers/voyage_nitro_black3.webp" },
        { productImg: "/sneakers/voyage_nitro_black4.webp" },
        { productImg: "/sneakers/voyage_nitro_black5.webp" },
      ],
      img: "/sneakers/deviat_nitro.webp",
      model: "Sneakers Deviate Nitro Wtr Men's Running Shoes",
      color: "Puma Black",
      sizeSelection: [
        {
          sizeEur: 39,
          sizeUK: 6,
          sizeCountInStock: 6,
        },
        {
          sizeEur: 40,
          sizeUK: 6.5,
          sizeCountInStock: 2,
        },
        {
          sizeEur: 41,
          sizeUK: 7.5,
          sizeCountInStock: 2,
        },
        {
          sizeEur: 42,
          sizeUK: 8,
          sizeCountInStock: 5,
        },
        {
          sizeEur: 43,
          sizeUK: 9,
          sizeCountInStock: 1,
        },
        {
          sizeEur: 44,
          sizeUK: 9,
          sizeCountInStock: 9,
        },
      ],
      atr: "195572_01",
      alt: "Sneakers Deviate Nitro Wtr Men's Running Shoes",
      blur: { blurData3 },
      newPrice: 3390,
      oldPrice: 7690,
      newPriceString: "3 390,00 ₴",
      oldPriceString: "7 690,00 ₴",
      sale: "-53%",
    },
    {
      id: uuidv4(),
      slug: "sneakers-deviate-nitro-wtr-men-s-running-shoes",
      imgProductPage: [
        { productImg: "/sneakers/deviat_nitro.webp" },
        { productImg: "/sneakers/voyage_nitro_black1.webp" },
        { productImg: "/sneakers/voyage_nitro_black2.webp" },
        { productImg: "/sneakers/voyage_nitro_black3.webp" },
        { productImg: "/sneakers/voyage_nitro_black4.webp" },
        { productImg: "/sneakers/voyage_nitro_black5.webp" },
      ],
      img: "/sneakers/deviat_nitro.webp",
      model: "Sneakers Deviate Nitro Wtr Men's Running Shoes",
      color: "Puma Black",
      sizeSelection: [
        {
          sizeEur: 39,
          sizeUK: 6,
          sizeCountInStock: 6,
        },
        {
          sizeEur: 40,
          sizeUK: 6.5,
          sizeCountInStock: 2,
        },
        {
          sizeEur: 41,
          sizeUK: 7.5,
          sizeCountInStock: 2,
        },
        {
          sizeEur: 42,
          sizeUK: 8,
          sizeCountInStock: 5,
        },
        {
          sizeEur: 43,
          sizeUK: 9,
          sizeCountInStock: 1,
        },
        {
          sizeEur: 44,
          sizeUK: 9,
          sizeCountInStock: 9,
        },
      ],
      atr: "195572_01",
      alt: "Sneakers Deviate Nitro Wtr Men's Running Shoes",
      blur: { blurData3 },
      newPrice: 3390,
      oldPrice: 7690,
      newPriceString: "3 390,00 ₴",
      oldPriceString: "7 690,00 ₴",
      sale: "-53%",
    },
    {
      id: uuidv4(),
      slug: "sneakers-twitch-runner-running-shoes",
      imgProductPage: [
        { productImg: "/sneakers/deviat_nitro.webp" },
        { productImg: "/sneakers/voyage_nitro_black1.webp" },
        { productImg: "/sneakers/voyage_nitro_black2.webp" },
        { productImg: "/sneakers/voyage_nitro_black3.webp" },
        { productImg: "/sneakers/voyage_nitro_black4.webp" },
        { productImg: "/sneakers/voyage_nitro_black5.webp" },
      ],
      img: "/sneakers/twitch_nitro.webp",
      model: "Sneakers Twitch Runner Running Shoes",
      color: "Peacoat Puma White",
      sizeSelection: [
        {
          sizeEur: 39,
          sizeUK: 6,
          sizeCountInStock: 6,
        },
        {
          sizeEur: 40,
          sizeUK: 6.5,
          sizeCountInStock: 2,
        },
        {
          sizeEur: 41,
          sizeUK: 7.5,
          sizeCountInStock: 2,
        },
        {
          sizeEur: 42,
          sizeUK: 8,
          sizeCountInStock: 5,
        },
        {
          sizeEur: 43,
          sizeUK: 9,
          sizeCountInStock: 1,
        },
        {
          sizeEur: 44,
          sizeUK: 9,
          sizeCountInStock: 9,
        },
      ],
      atr: "195572_01",
      alt: "Sneakers Deviate Nitro Wtr Men's Running Shoes",
      blur: { blurData3 },
      newPrice: 3390,
      oldPrice: 7690,
      newPriceString: "3 390,00 ₴",
      oldPriceString: "7 690,00 ₴",
      sale: "-53%",
    },
    // {
    //   id: uuidv4(),
    //   slug: "sneakers-twitch-runner-running-shoes",
    //   imgProductPage: [
    //     { productImg: "/sneakers/deviat_nitro.webp" },
    //     { productImg: "/sneakers/voyage_nitro_black1.webp" },
    //     { productImg: "/sneakers/voyage_nitro_black2.webp" },
    //     { productImg: "/sneakers/voyage_nitro_black3.webp" },
    //     { productImg: "/sneakers/voyage_nitro_black4.webp" },
    //     { productImg: "/sneakers/voyage_nitro_black5.webp" },
    //   ],
    //   img: "/sneakers/twitch_nitro.webp",
    //   model: "Sneakers Twitch Runner Running Shoes",
    //   color: "Peacoat-Puma White",
    //   sizeSelection: [
    //     {
    //       sizeEur: 39,
    //       sizeUK: 6,
    //       sizeCountInStock: 6,
    //     },
    //     {
    //       sizeEur: 40,
    //       sizeUK: 6.5,
    //       sizeCountInStock: 2,
    //     },
    //     {
    //       sizeEur: 41,
    //       sizeUK: 7.5,
    //       sizeCountInStock: 2,
    //     },
    //     {
    //       sizeEur: 42,
    //       sizeUK: 8,
    //       sizeCountInStock: 5,
    //     },
    //     {
    //       sizeEur: 43,
    //       sizeUK: 9,
    //       sizeCountInStock: 1,
    //     },
    //     {
    //       sizeEur: 44,
    //       sizeUK: 9,
    //       sizeCountInStock: 9,
    //     },
    //   ],
    //   atr: "195572_01",
    //   alt: "Sneakers Deviate Nitro Wtr Men's Running Shoes",
    //   blur: { blurData3 },
    //   newPrice: 3390,
    //   oldPrice: 7690,
    //   newPriceString: "3 390,00 ₴",
    //   oldPriceString: "7 690,00 ₴",
    //   sale: "-53%",
    // },
  ],
};

export default data;
